[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/proposal/*/accept"
  to = "/.netlify/functions/proposal-accept"
  status = 200

[[redirects]]
  from = "/api/proposal/*"
  to = "/.netlify/functions/proposal"
  status = 200

[[redirects]]
  from = "/est/*"
  to = "/index.html"
  status = 200